# More detail regarding the app.yaml can be found here:
# https://cloud.google.com/appengine/docs/standard/java11/config/appref
runtime: java11
instance_class: B1

includes:
  # environment variables are stored separately from the repository
  # for security purposes, these should never be added to the gir repo
  - env_variables.yaml